import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost/opencart/upload/');
  await page.getByRole('link', { name: ' My Account ' }).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).click();
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('correa');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).press('Alt+6');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).press('Alt+4');
  await page.getByRole('textbox', { name: 'E-Mail Address' }).fill('correa@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Your Store' }).click();
  await page.getByRole('link', { name: 'Tablets' }).click();
  await page.getByRole('link', { name: 'Laptops & Notebooks (5)' }).click();
  await page.getByRole('link', { name: 'HP LP3065' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: ' 1 item(s) - $' }).click();
  await page.getByRole('link', { name: ' View Cart' }).click();
  await page.getByRole('link', { name: 'Checkout', exact: true }).click();
  await page.getByRole('textbox', { name: '* First Name' }).click();
  await page.getByRole('textbox', { name: '* First Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* First Name' }).fill('M');
  await page.getByRole('textbox', { name: '* First Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* First Name' }).fill('Maria');
  await page.getByRole('textbox', { name: '* Last Name' }).click();
  await page.getByRole('textbox', { name: '* Last Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* Last Name' }).fill('C');
  await page.getByRole('textbox', { name: '* Last Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* Last Name' }).fill('Correa');
  await page.getByRole('textbox', { name: '* Address' }).click();
  await page.getByRole('textbox', { name: '* Address' }).fill('calle valle grande-sucre');
  await page.getByRole('textbox', { name: '* City' }).click();
  await page.getByRole('textbox', { name: '* City' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* City' }).fill('S');
  await page.getByRole('textbox', { name: '* City' }).press('CapsLock');
  await page.getByRole('textbox', { name: '* City' }).fill('Sucre');
  await page.getByLabel('Country').selectOption('26');
  await page.getByRole('textbox', { name: 'Post Code' }).click();
  await page.getByRole('textbox', { name: 'Post Code' }).fill('0000');
  await page.getByLabel('Region / State').selectOption('404');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#button-shipping-methods').click();
  await page.getByText('Flat Shipping Rate - $').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#button-payment-methods').click();
  await page.locator('label').filter({ hasText: 'Cash On Delivery' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Add Comments About Your Order' }).click();
  await page.getByRole('textbox', { name: 'Add Comments About Your Order' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Add Comments About Your Order' }).fill('P');
  await page.getByRole('textbox', { name: 'Add Comments About Your Order' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Add Comments About Your Order' }).fill('Producto fragil');
  await page.getByRole('button', { name: 'Confirm Order' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
});