name: Playwright Tests

# Eventos que disparan el workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Instalar navegadores de Playwright
      - name: Install Playwright Browsers
        run: npx playwright install

      # 5️⃣ Ejecutar los tests de Playwright
      - name: Run Playwright Tests
        run: npx playwright test --reporter=list

      # 6️⃣ (Opcional) Guardar los resultados como artefactos
      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-report/
