name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Node.js (misma versión que tu PC)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3️⃣ Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4️⃣ Verificar versión de Playwright
      - name: Check Playwright Version
        run: npm run playwright:version

      # 5️⃣ Instalar navegadores de Playwright
      - name: Install Playwright Browsers
        run: npm run playwright:install

      # 6️⃣ Ejecutar los tests de Playwright
      - name: Run Playwright Tests
