name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # 👇 Verificar que Playwright está instalado
      - name: Check Playwright Version
        run: npm run playwright:version

      # 👇 Instalar navegadores de Playwright
      - name: Install Playwright Browsers
        run: npm run playwright:install

      # 👇 Ejecutar los tests
      - name: Run Playwright Tests
        run: npm run test:e2e

      # 👇 Subir reporte como artefacto
      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-report/
